language: c
os: osx

before_install:
  - wget https://github.com/chrmoritz/starcheat/releases/download/4f7bd31/local_pyqt5.tar.gz
  - unset PYTHONPATH
  - brew update

install:
  - brew install python3
  - sudo tar xf local_pyqt5.tar.gz -C /usr
  - pip3 install Pillow
  - pip3 install py2app

script:
  - mac/travis.rb

branches:
  only:
    - /^v?\d+(\.\d+)*$/

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/starcheat-$TRAVIS_BRANCH-osx.tar.gz
  on:
    tags: true
