language: c
os: osx

before_install:
  - wget https://github.com/chrmoritz/starcheat/releases/download/4f7bd31/local_cache.tar.gz
  - unset PYTHONPATH

install:
  - sudo tar xf local_cache.tar.gz -C /usr
  - cd /usr/local
  - git reset --hard FETCH_HEAD
  - git clean -df
  - brew update
  - curl https://raw.githubusercontent.com/Homebrew/homebrew/3bac79f/Library/Formula/qt5.rb -o Library/Formula/qt5.rb
  - cat Library/Formula/qt5.rb
  - brew outdated
  - brew unlink python3
  - brew link gdbm
  - brew unlink xz
  - brew upgrade python3
  - brew unlink sip
  - brew upgrade sip
  - brew unlink pyqt5
  - brew upgrade pyqt5
  - cd $TRAVIS_BUILD_DIR

script:
  - mac/travis.rb

branches:
  only:
    - /^v?\d+(\.\d+)*$/

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/starcheat-$TRAVIS_BRANCH-osx.tar.gz
  on:
    tags: true
