language: objective-c
before_install:
  - brew update
env:
  secure: "Fn+fj+RxBAW7OvVby9JVcCl13jGJOEB3tNE93tYfNXhpCHXgJ3Ip4uzp29v0TnHa0UTy9iaQwG6WZn1pgh2sY+U+mTcrNERbPupPOU7TBpPOMhU96xtF5s6ozSgj7B4Prcf8GEpauSUTR5FI/pd5raEFV/yWUEt3f6Kj9cIMAkk="
install:
  - brew install python3 qt5
  - brew install https://raw.github.com/chrmoritz/starcheat/cache/mac/pyqt5.rb
script:
  - brew install -v https://raw.github.com/chrmoritz/starcheat/cache/mac/starcheat.rb --with-dist
  - sudo brew test -v https://raw.github.com/chrmoritz/starcheat/cache/mac/starcheat.rb --with-dist
  - curl -O https://raw.github.com/chrmoritz/starcheat/cache/upload.sh
  - chmod +x upload.sh
  - sudo ./upload.sh
