language: objective-c
before_install:
  - brew update
env:
  secure: "Vr4x56j8fe0pwxkN3eYgrhtWRCMEg/lMeahqtlHJNcObXEfzwoldm1n81N19gYCg0easumMrij72FTok/GKa3x3Yc0FNvlt6v2miP4O2jY7QtBTviaLaJb1Y5Intqchb8OLRPspaG99MZ/2BvuM279q6lpCSL1uWUXhd8KuE/7k="
install:
  - brew ls
  - brew remove apple-gcc42 cmake libgpg-error mercurial sqlite
  - brew remove appledoc git libksba subversion libyaml
  - brew remove autoconf go libtool automake lcov xctool
script:
  - brew install -v mac/cache.rb
  - sudo ./mac/upload.sh
