language: objective-c

before_install:
  - wget https://github.com/chrmoritz/starcheat/releases/download/4f7bd31/local_cache_test.tar.gz
  - unset PYTHONPATH

install:
  - sudo tar xf local_cache_test.tar.gz -C /usr

script:
  - mac/travis.rb

branches:
  only:
    - /^v?\d+(\.\d+)*$/

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: EcekaffVmDS4u+y1sPVFQDRko+eSrw56DwKwKHyFIZKuOSx5u3dEzxn1JG9ho43lllhowjnXp40JhMSOheigkbVj22LOmheGWsdJiOt71PXHpXMuzsnB53hTHxqPW4szXs8MHlVWA9Kg8Dstda7S2RYalSP/50NYNLKVdaCSyuY=
  file: build/starcheat-$TRAVIS_BRANCH-osx.tar.gz
  on:
    repo: chrmoritz/starcheat
    tags: true
    all_branches: true
